[package]
name = "alpheratz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "=0.5.0-rc.4", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
alphe = { path = "./alphe" }